version: "3"
services:
  agent:
    image: grafana/agent:v0.22.0
    volumes:
      - "./agent.yaml:/etc/agent-config/agent.yaml:ro,rslave"
      - "/:/host/root:ro,rslave"
      - "/sys:/host/sys:ro,rslave"
      - "/proc:/host/proc:ro,rslave"
      - "/tmp/agent:/etc/agent"
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
    network_mode: "host"
    pid: "host"
    cap_add:
      - SYS_TIME
