version: '3'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=linus
      - POSTGRES_PASSWORD=42secret
      - POSTGRES_DB=postgres

  mysql:
    image: mysql:8.0
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=42secret
      - MYSQL_DATABASE=test

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  postfixadmin:
    image: postfixadmin
    ports:
      - 8000:80
    restart: always